### PR TITLE
Upgrade licensee

### PR DESCRIPTION
**Pull request by yashkohli88**
Updated Dockerfile and DevDockerfile in order to update licensee which is one of the scanning tool that crawler uses from version 9.12.0 to 9.16.1. Ruby is also updated from 2.5.4 to 3.2.2. Details for this update can be found [https://github.com/clearlydefined/crawler/issues/536](#536 )

### CODE REVIEW

**Comment by qtomlinson** [comment]
Task: https://github.com/clearlydefined/crawler/issues/536

**Review by lumaxis — APPROVED** [review]

**Review by elrayle — APPROVED** [review]
LGTM!  Great to see another dependency updated.  Thanks for the very thorough analysis.

**Comment by elrayle** [comment]
@yashkohli88 @qtomlinson This looks ready to merge.  Any reason to hold off?

**Comment by qtomlinson** [comment]
@elrayle Upon merging of the PR, integration tests need to be upgraded to prevent failure.

**Pull request merged**
