### PR TITLE
Add reuse to goExtract and podExtract

### PR DESCRIPTION
**Pull request by qtomlinson**

### CODE REVIEW

**Comment by qtomlinson** [comment]
@disulliv @SebastianWolf-SAP ready for review.

**Review by disulliv — APPROVED** [review]
I never noticed that Pod doesn't have any tests, but I wouldn't consider that a problem to deal with in this PR. Thanks for catching the Go & Pod types and making these changes :)

**Comment by qtomlinson** [comment]
I am adding pod test in my other [PR](https://github.com/clearlydefined/crawler/pull/467). 
See https://github.com/clearlydefined/crawler/pull/467/files#diff-8fb9d5533580ab6a148da36cba21527f3168235ca99fe9a0ea2f6c795e1fa8b1

**Comment by qtomlinson** [comment]
@disulliv anything I should add before this can be merged?

**Comment by disulliv** [comment]
All good! Wasn't sure if others wanted to take a look too.

**Pull request merged**
