### PR TITLE
Derive license from info.license over classifiers in pypi registry data

### PR DESCRIPTION
**Pull request by qtomlinson**
Based on the [Python Packaging User Guide](https://packaging.python.org/en/latest/specifications/core-metadata/#license), it appears that the license field holds more specific information.  Change to parsing license field before the classifiers.  When classifier has the version info and the license field does not, use classifier first in that case.

Also updated the toolVersion in pypiExtract.

Task: #523 
Task: #519 
Task: #429

### CODE REVIEW

**Comment by qtomlinson** [comment]
Here are the extract license information for 1000 [pypi components](https://github.com/user-attachments/files/16617404/licenses2.json).  The structure of each entry is as follows:
```
{
    "coordinates": "clearlydefined coordinates",
    "info.license": "info.license field from pypi registry data",
    "info.classifiers": "license extracted from info.classifiers field in pypi registry data"
}
```

**Comment by qtomlinson** [comment]
Please find a more detailed JSON file with extracted SPDX licenses from the specified fields here: [licenses3.json](https://github.com/user-attachments/files/16626721/licenses3.json). In 150 instances, the non-empty SPDX licenses from the info.license field differ from those in the info.classifiers field. It appears that the licenses from the info.license field provide more detailed information.

**Comment by Jeffrey-Luszcz** [comment]
I think we have a BSD vs BSD-2 vs BSD-3 clause problem we need to figure out how to handle. By reviewing the JSON file I see data with the following styles of problems:

License in repo is BSD-3 [ https://github.com/encode/starlette/blob/master/LICENSE.md ]but json says variously BSD & BSD-2:  
{
    "coordinates": "pypi/pypi/-/starlette/0.38.0",
    "info.classifiers": " BSD License",
    "info.license": null,
    "spdxFomClassifier": "BSD-2-Clause",
    "versionInClassifier": false,
    "versionInLicenseInfo": false
  },


List in repo is BSD-3 [ https://github.com/andialbrecht/sqlparse/blob/master/LICENSE ] but JSON says BSD or BSD-2
  {
    "coordinates": "pypi/pypi/-/sqlparse/0.5.1",
    "info.classifiers": " BSD License",
    "info.license": null,
    "spdxFomClassifier": "BSD-2-Clause",
    "versionInClassifier": false,
    "versionInLicenseInfo": false
  },

License in repo is BSD-3 [ https://github.com/google/re2/blob/main/LICENSE ]but json says variously BSD & BSD-2:  
  {
    "coordinates": "pypi/pypi/-/google-re2/1.1.20240702",
    "info.classifiers": " BSD License",
    "info.license": null,
    "spdxFomClassifier": "BSD-2-Clause",
    "versionInClassifier": false,
    "versionInLicenseInfo": false
  },

**Comment by Jeffrey-Luszcz** [comment]
Also for LGPL we have a similar problem 

https://pypi.org/project/astroid/ License on pypi.org says "License: GNU Lesser General Public License v2 (LGPLv2) (LGPL-2.1-or-later)" but there's a mix of 2.0 and 2.1 and only and + in the json
 {
    "coordinates": "pypi/pypi/-/astroid/3.2.4",
    "info.classifiers": " GNU Lesser General Public License v2 (LGPLv2)",
    "info.license": "LGPL-2.1-or-later",
    "spdxFomClassifier": "LGPL-2.0-only",
    "versionInClassifier": true,
    "spdxFromLicenseInfo": "LGPL-2.1-or-later",
    "versionInLicenseInfo": true
  },

**Comment by qtomlinson** [comment]
@Jeffrey-Luszcz This pull request is focused on extracting license information from the core metadata of the Python registry. This does not involve inspecting the license file, as that task is handled by other tools such as Licensee and ScanCode. The discrepancies you mentioned here are related to the cases where there is a mismatch between the registry metadata and the license file.

**Comment by Jeffrey-Luszcz** [comment]
To close out this issue on my side. I support the change described (e.g. Derive license from info.license over classifiers)
@qtomlinson thanks for pulling together the json data, it really makes it clear.

My point in the comments above is that we should take another look at the mapping we have when we have a bare "BSD" license declared in these fields. We currently map it to BSD-2 and likely should map it to BSD-3 (the more common license choice) 
This is a separate issue and I'll open one for discussion.

**Review by elrayle — APPROVED** [review]
This all looks good.  Thanks for adding tests to capture the new possible conditions.

**Pull request merged**
